### ISSUE TITLE
目前现存的一些问题

### ISSUE THREAD

**Issue by cppla** [zeyudada/StatusServerLayui#1]
IOS字体不协调：

https://api.cloudcpp.com/cache/123694533954240516.jpeg
https://api.cloudcpp.com/cache/123694533954241536.jpeg

**Comment by zeyudada** [comment]
我手上没有ios设备，没法复现啊。。。我加了个-webkit-text-size-adjust: none;，已经放到示例界面了，你再试试
关于4k屏幕下字太小，字体大小是固定的，屏幕太大了自然会导致字相对变小了。。。
4k屏应该可以调dpi
原来的界面也是4k屏不兼容
![image](https://user-images.githubusercontent.com/64437653/236385369-0b90f0ea-5d2a-403a-bf6f-8ef29157bba7.png)

**Comment by cppla** [comment]
嗯呢，下午抽时间我先看下IOS 为什么字体会这么不协调。
